### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by astrodotexe** [echasnovski/nvim#3]

**Comment by echasnovski** [comment]
Hi!

------

To change color scheme, you first have to install one you would like and then follow its configuration instructions.
Installation is done as any other plugin. There are at least two choices here:
- Use plugin manager . [folke/lazy.nvim](https://github.com/folke/lazy.nvim) and [wbthomason/packer.nvim](https://github.com/wbthomason/packer.nvim) are two popular choices nowadays.
- Use built-in package feature. I recommend creating '~/.config/nvim/pack/plugins/opt', then cloning plugin repository as its subdirectory, and make your config recognize it by executing `packadd <name>`. Example using 'mini.nvim" (assuming Unix-type OS):
    ```
    mkdir -p ~/.config/nvim/pack/plugins/opt
    git clone --depth 1 https://github.com/echasnovski/mini.nvim.git ~/.config/nvim/pack/plugins/opt/mini.nvim
    ```
    And then add `vim.cmd('packadd mini.nvim')` in your 'init.lua'.

After that, using `:colorscheme` command with color scheme name makes it active. Following example, add `vim.cmd('colorscheme minischeme')`.

------

I am not sure what you mean by cursor animation. I guess there are two choices here:

- If you want to customize cursor blinking, see ['guicursor'](https://neovim.io/doc/user/options.html#'guicursor') option.
- If you want to customize 'mini.animate' cursor animation, see documentation [about cursor animation](https://github.com/echasnovski/mini.nvim/blob/305debd01d486f94a9f6ecfec90321ea98dc5dd9/doc/mini-animate.txt#L200) and [about some built-in animation paths](https://github.com/echasnovski/mini.nvim/blob/305debd01d486f94a9f6ecfec90321ea98dc5dd9/doc/mini-animate.txt#L623).

------

> How can i use lingature like Fira Code Nerd Font.

It is not a Neovim question, but a general terminal emulator one. This needs two ingredients:
- Terminal emulator that supports ligatures. Two popular choices nowadays are [kitty](https://github.com/kovidgoyal/kitty) and [Alacritty](https://github.com/alacritty/alacritty).
- Font that has ligatures, like Fira Code Nerd Font, yes. It should be configured as main one for terminal emulator.

------

For more information about how to use Lua for Neovim config, please see [nanotee/nvim-lua-guide](https://github.com/nanotee/nvim-lua-guide) or run `:h lua-guide` if you have Neovim at least 0.8.2 version.

**Comment by michaelphandeveloper** [comment]
Thank you Evgeni Chasnovski, i'll try.

**Comment by michaelphandeveloper** [comment]
i success at setup gruvbox as my main colorscheme, but i git clone packer.nvim in <~\AppData\Local\nvim\pack\plugins\opt\packer.nvim> then i write packadd(packer.nvim') in packadd.lua and vim.cmd [[packadd packer.nvim]] in settings.lua and run PackerInstall but it shown not an editor command. Moreover how can i add use '.......' in packer as usual.

**Comment by michaelphandeveloper** [comment]
i hope you make a video (if you have freetime) about how to setting neovim using lua as your Neovim settups https://github.com/echasnovski/nvim. Your Neovim setup video might have thousand of viewers. I read your Neovim repo but some of fuctions or code logic i misunderstood. I really like how you comment and explain detail in your code. I am your first viewer and subscriber if you make video. Thankssss. ^_^

**Comment by echasnovski** [comment]
> i success at setup gruvbox as my main colorscheme, but i git clone packer.nvim in <~\AppData\Local\nvim\pack\plugins\opt\packer.nvim> then i write packadd(packer.nvim') in packadd.lua and vim.cmd [[packadd packer.nvim]] in settings.lua and run PackerInstall but it shown not an editor command. Moreover how can i add use '.......' in packer as usual.

I am not sure what file structure you have in your config. I recommend starting with a single '~/AppData/Local/nvim/init.lua' and use only `vim.cmd('packadd packer.nvim')`. Or more appropriately, recreate steps from [packer's "Quickstart"](https://github.com/wbthomason/packer.nvim#quickstart).



> i hope you make a video (if you have freetime) about how to setting neovim using lua just like your Neovim setups https://github.com/echasnovski/nvim. Your Neovim setup video might have thousand of viewers. I read your Neovim repo but some of fuctions or code logic i misunderstood. I really like how you comment and explain detail in your code. I am your first viewer and subscriber if you make video for sure. Thankssss. ^_^

Thanks for kind words, but I don't think it will happen any time soon. Will have in mind though :)

**Comment by michaelphandeveloper** [comment]
Thank you 🧢

**Comment by devemichael** [comment]
Hi @echasnovski, i just reopen this thread because i want to delete this issue or discussion but i cant (Github said that i need to contact the owner), i want to renew my Github page for my CV. Thanks and have a good day.

**Comment by devemichael** [comment]
Thanks for helping me and i really sorry if it bother you.
