### ISSUE TITLE
Github copilot

### ISSUE THREAD

**Issue by saifulapm** [echasnovski/nvim#6]
Hi, I love your minimal config. It is possible to integrate copilot.lua with mini.completion ?

Thanks

**Comment by echasnovski** [comment]
Thanks for the feedback!

The answer is no, as 'mini.completion' is built to support only two sources: 'LSP' and a fallback (by default - built-in `<C-n>` completion). This likely won't change.

You can look for way to integrate Copilot in the Neovim config in [Awesome Neovim](https://github.com/rockerBOO/awesome-neovim).
